<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Apizr" />
    <PackageReference Include="Apizr.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="Apizr.Integrations.FileTransfer.MediatR" />
    <PackageReference Include="Apizr.Integrations.Fusillade" />
    <PackageReference Include="Apizr.Integrations.MediatR" />
    <PackageReference Include="Fido2.Models" />
    <PackageReference Include="Fody">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ConfigureAwait.Fody" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Ixnas.AltchaNet" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="WTorricos.Results" />
  </ItemGroup>

  <ItemGroup>
    <None Update="**/FodyWeavers.*" Visible="false" />
    <None Update="**/.refitter*" Visible="false" />
    <Localize Include="Resources\TranslationResources_*.json" NamespaceName="snowcoreBlog.PublicApi.Resources" ClassName="TranslationResources" NeutralCulture="en" />
  </ItemGroup>

</Project>